---

- name: Get installed version of GammuSMSD.
  command: /usr/bin/env gammu-smsd --version
  when: ansible_local.gammu_smsd is not defined
  changed_when: False
  check_mode: False
  register: _gammu_smsd__version

- name: Create gammu_smsd__version variable
  set_fact:
    gammu_smsd__version: "{{ _gammu_smsd__version.stdout_lines[0]|regex_replace('^Gammu-smsd\\s+version\\s+([0-9.]+)$', '\\1') if _gammu_smsd__version is not skipped else ansible_local.gammu_smsd.version_full }}"


## common configuration

- name: Ensure configuration directory exists
  file:
    path:  '{{ gammu_smsd__configuration_directory }}'
    owner: root
    group: root
    mode:  '0755'
    state: directory

- name: Ensure var directory exists
  file:
    path:  '{{ gammu_smsd__var_directory }}'
    owner: root
    group: root
    mode:  '0755'
    state: directory

- name: Remove packages configurations files
  file:
    path:  '{{ item }}'
    state: absent
  with_items:
    - /etc/gammu-smsdrc

- name: Install gammu-smsd environment file
  template:
    src:   gammu-smsd.environment.j2
    dest:  '{{ gammu_smsd__service_environment }}'
    owner: root
    group: root
    mode:  0644
  when: gammu_smsd__service_environment is defined
  notify: [ 'restart-gammu-smsd' ]
