---
# tasks file for gammu-smsd

- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      skip: true
  tags: ['always']

- import_tasks: init.yml
  tags: ['always']

- import_tasks: install.yml
  tags: ['gammu-smsd', 'gammu-smsd-install']

- import_tasks: configure.yml
  tags: ['gammu-smsd', 'gammu-smsd-configure']

- import_tasks: service.yml
  tags: ['gammu-smsd', 'gammu-smsd-service']

- include_tasks: facts.yml
  when: gammu_smsd__facts|bool
