---
# tasks file for gammu-smsd

- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- import_tasks: init.yml
  tags: ['always']

- name: Run apt-backports
  include_role:
    name: apt-backports
  when: ansible_os_family in ['Debian'] and gammu_smsd__packages_allow_backports|bool
  tags: ['gammu-smsd', 'gammu-smsd-install']

- import_tasks: install.yml
  tags: ['gammu-smsd', 'gammu-smsd-install']

- import_tasks: configure.yml
  tags: ['gammu-smsd', 'gammu-smsd-configure']

- import_tasks: service.yml
  tags: ['gammu-smsd', 'gammu-smsd-service']

- include_tasks: instance.yml
  vars:
    gammu_smsd__instance: "{{ gammu_smsd__instance_defaults|combine(outer_item.value)|combine({'name': outer_item.key}) }}"
  with_dict: '{{ gammu_smsd__instances }}'
  loop_control:
    loop_var: outer_item
  tags: ['gammu-smsd', 'gammu-smsd-configure']

- include_tasks: 'monitoring/monitoring-{{ gammu_smsd__monitoring }}.yml'
  when: gammu_smsd__monitoring is defined
  tags: ['gammu-smsd', 'gammu-smsd-monitoring']

- include_tasks: facts.yml
  when: gammu_smsd__facts|bool
  tags: ['gammu-smsd', 'gammu-smsd-facts']
