---

- name: Install gammu-smsd.service systemd unit file
  template:
    src:   gammu-smsd.service.j2
    dest:  "/etc/systemd/system/{{ gammu_smsd__service_name|replace('%i', '') }}.service"
    owner: root
    group: root
    mode:  0755
  when: gammu_smsd__service_configure_systemd|bool and ansible_service_mgr == 'systemd'
  register: _gammu_smsd__service
  notify: [ 'restart-gammu-smsd' ]

- name: Remove sysvinit unit file
  file:
    path:  /etc/init.d/gammu-smsd
    state: absent
  when: gammu_smsd__service_configure_systemd|bool and ansible_service_mgr == 'systemd'
  notify: [ 'restart-gammu-smsd' ]

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: _gammu_smsd__service is changed and ansible_service_mgr == 'systemd'
